"""Añade campo active a Usuario

Revision ID: 14762a8840c7
Revises: 40ef772c4345
Create Date: 2023-10-14 15:58:34.013963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14762a8840c7'
down_revision = '40ef772c4345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
