"""Añade el campo user_id a boqueo model

Revision ID: 3e55d54dd4e5
Revises: 7cc3d9e54afd
Create Date: 2023-11-06 23:54:05.715551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e55d54dd4e5'
down_revision = '7cc3d9e54afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_day', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
