"""Establecimiento de relaciones

Revision ID: d769c7287ce5
Revises: 3e55d54dd4e5
Create Date: 2023-11-17 11:41:07.048671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd769c7287ce5'
down_revision = '3e55d54dd4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('peluquero',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'usuario', ['peluquero'], ['id'])

    with op.batch_alter_table('blocked_day', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuario', ['user_id'], ['id'])

    with op.batch_alter_table('horario', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuario', ['userId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('blocked_day', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('peluquero',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
